WITH A AS
(SELECT SCHEDULED_AT, SUM(PRICE) AS TOTAL_PRICE, COUNT(*) AS CNT
FROM SCHEDULES
GROUP BY SCHEDULED_AT
ORDER BY SCHEDULED_AT DESC)

SELECT SCHEDULED_AT, ROUND(TOTAL_PRICE/10, 0) AS INCENTIVE
FROM A
WHERE CNT >= 3
ORDER BY INCENTIVE DESC, SCHEDULED_AT DESC